#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for src/backend/vprofiler
#
# IDENTIFICATION
#    src/backend/vprofiler/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/vprofiler
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global
override CPPFLAGS := -std=c++11 $(CPPFLAGS)

OBJS = trace_tool.o

include $(top_srcdir)/src/backend/common.mk
